### ISSUE TITLE
apps/recipes

### ISSUE THREAD

**Issue by obfusk** [obfusk/rbtlog#35]
- [ ] com.amaze.filemanager -> build ID, LLD build path, gradle wrapper
- [x] org.netdex.androidusbscript
- [ ] in.hridayan.ashell -> tag mismatch, resource file names and PNGs, AAPT error, **disabled**
- [ ] fr.dzx.audiosource -> AGP too old, PNGs, ???
- [x] com.cominatyou.batterytile
- [x] f.cking.software
- [x] org.breezyweather -> ~~timestamps~~, local.properties
- [x] com.danilkinkin.buckwheat -> ~~res/X9.ttf compresslevel=unknown~~, no gradle wrapper
- [x] me.hackerchick.catima -> commit hash mismatch on v2.28.0
- [x] com.meenbeese.chronos -> missing dependencies
- [x] com.sosauce.cutecalc -> tag mismatch
- [x] at.bitfire.davdroid -> ~~flaky~~, ~~timestamps~~
- [x] com.looker.droidify -> ~~locales (fixed)~~
- [x] eu.faircode.email -> ~~build ID~~, JAR
- [x] dev.jdtech.jellyfin -> ~~timestamps~~, AAR
- [x] se.nullable.flickboard -> ???
- [x] org.handmadeideas.floccus -> ~~icon~~
- [ ] dev.patrickgold.florisboard.beta -> big DEX diff, timestamps, build ID, commit hash, needs rust, **disabled**
- [x] org.fossify.calculator
- [x] org.fossify.calendar
- [x] org.fossify.clock
- [x] org.fossify.contacts
- [x] org.fossify.filemanager
- [x] org.fossify.gallery
- [x] org.fossify.keyboard
- [x] org.fossify.home
- [x] org.fossify.musicplayer -> pg-map-id
- [x] org.fossify.notes
- [x] org.fossify.phone
- [x] org.fossify.messages
- [ ] org.fossify.voicerecorder -> tag mismatch
- [x] io.freetubeapp.freetube
- [x] com.vishal2376.gitcoach -> .profm (needs upstream fix)
- [x] com.benlinskey.greekreference -> JARs & ZIPs
- [x] com.starry.greenstash
- [x] helium314.keyboard
- [ ] ru.application.homemedkit -> ~~local.properties~~, commit hash mismatch, compose-destinations UUID, **disabled**
- [x] in.sunilpaulmathew.izzyondroid
- [x] com.jerboa
- [x] com.sjapps.jsonlist -> small patch for v1.4 tag mismatch
- [x] dev.zwander.lemmyredirect -> ~~build UUID~~
- [x] dev.medzik.librepass.android
- [x] com.github.libretube -> commit hash mismatch on >= v0.22.1
- [x] com.martinmimigames.simplefileexplorer
- [ ] com.github.whitescent.mastify -> tag mismatch, previous release is RB, can't build w/ firebase added, **disabled**
- [x] dev.zwander.mastodonredirect -> ~~build UUID~~
- [x] com.zell_mbc.medilog
- [x] projects.medicationtracker -> build ID
- [x] com.futsch1.medtimer -> ~~requires AnyChart license key~~
- [x] ara.memoryguardian
- [x] juniojsv.minimum
- [x] org.joinmastodon.android.moshinda
- [x] com.sanmer.mrepo -> **disabled**
- [x] com.starry.myne
- [ ] com.machiav3lli.backup -> ~~locales & missing files~~
- [x] com.machiav3lli.fdroid -> ~~annotation (?!)~~, ~~locales (see droidify)~~, hash/.version mismatch
- [x] com.craxiom.networksurvey -> ~~version code/name updated after tagging~~, ~~google-services.json~~
- [x] com.hardbacknutter.nevertoomanybooks -> ~~timestamps~~, ~~.prof differs for v6.0.0~~
- [x] com.gero.newpass -> version code/name updated after tagging, security issues
- [x] com.limo.notecompanion -> no gradle wrapper
- [ ] kittoku.osc -> ??? (tiny diff), previous release is RB
- [x] io.github.devhyper.openvideoeditor
- [x] com.desarrollodroide.pagekeeper -> ~~.profm (needs upstream fix)~~
- [x] com.ladsers.passtable.android
- [x] uk.me.paraskos.pdfrenderer
- [x] dev.zwander.peertuberedirect -> ~~build UUID~~
- [x] com.github.axet.pingutils -> no gradle wrapper
- [ ] ac.mdiq.podcini -> commit hash / tag mismatch, eventbus, libconscrypt_jni.so, API keys, **disabled**
- [x] ru.karasevm.privatednstoggle
- [x] com.example.programmingtools -> no gradle wrapper, weird
- [ ] com.github.diegoberaldin.raccoonforlemmy.android -> ~~locales~~, embedded version is off, **disabled**
- [x] me.hackerchick.raisetoanswer
- [x] it.fast4x.rimusic -> tag/version mismatch on v0.6.25, bundletool JAR
- [x] in.basulabs.shakealarmclock
- [ ] com.vishal2376.snaptick -> big DEX diff (compose?)
- [x] com.bnyro.translate
- [x] de.grobox.liberario
- [x] de.hbch.traewelling -> JAR
- [x] org.polymorphicshade.tubular -> ~~flaky (desugaring)~~, hebrew symlink
- [ ] org.walkersguide.android -> ??? (tiny DEX diff), JAR
- [x] in.sunilpaulmathew.weatherwidget

---

- [x] org.schabi.newpipe -> ~~flaky (desugaring)~~
- [x] ch.threema.app.libre -> JARs/AARs

**Comment by Bin2jz** [comment]
> - [ ] com.amaze.filemanager -> build ID, LLD build path
> 
> - [x] me.hackerchick.catima
> 
> - [x] at.bitfire.davdroid -> flaky, timestamps
> 
> - [ ] com.looker.droidify -> locales (fixed)
> 
> - [ ] eu.faircode.email -> build ID
> 
> - [x] org.handmadeideas.floccus -> icon
> 
> - [x] org.fossify.calendar
> 
> - [x] org.fossify.contacts
> 
> - [x] org.fossify.filemanager
> 
> - [x] org.fossify.gallery
> 
> - [ ] org.fossify.musicplayer -> pg-map-id
> 
> - [x] org.fossify.phone
> 
> - [x] org.fossify.messages
> 
> - [ ] org.fossify.voicerecorder -> tag mismatch
> 
> - [ ] in.sunilpaulmathew.izzyondroid -> can't build
> 
> - [x] org.joinmastodon.android.moshinda
> 
> - [ ] com.machiav3lli.backup -> ???
> 
> - [ ] com.machiav3lli.fdroid -> annotation (?!), locales (see droidify)
> 
> - [x] it.fast4x.rimusic
> 
> - [x] in.basulabs.shakealarmclock
> 
> - [x] com.bnyro.translate
> 
> - [x] org.polymorphicshade.tubular -> flaky (desugaring), hebrew symlink
> 
> 
> 
> ---
> 
> 
> 
> - [ ] org.schabi.newpipe -> flaky (desugaring), ???
> 
> - [x] ch.threema.app.libre
